# Generated by Django 5.1.5 on 2025-02-06 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0002_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jjiapp.edition'),
        ),
    ]
