# Generated by Django 5.1.5 on 2025-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0005_edicion_parners_alter_edicion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
