# Generated by Django 5.1.5 on 2025-02-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0006_presentacion_abstract_presentacion_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
