# Generated by Django 5.1.5 on 2025-02-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0008_presentacion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='hora',
            field=models.TimeField(),
        ),
    ]
