# Generated by Django 5.1.5 on 2025-02-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0009_alter_presentacion_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='hora',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='hora_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
