# Generated by Django 5.1.5 on 2025-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0011_alter_presentacion_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='url_documento',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
