# Generated by Django 5.1.5 on 2025-02-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0013_alter_presentacion_url_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacion',
            name='url_documento',
        ),
        migrations.AddField(
            model_name='presentacion',
            name='manual',
            field=models.ImageField(null=True, upload_to='pdf'),
        ),
    ]
