# Generated by Django 5.1.5 on 2025-02-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0014_remove_presentacion_url_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentacion',
            old_name='manual',
            new_name='pdf',
        ),
    ]
