# Generated by Django 5.1.5 on 2025-02-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0020_alter_presentacion_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='jjiapp/static/pdf'),
        ),
    ]
