# Generated by Django 5.1.5 on 2025-02-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0022_presentacion_detalles_alter_presentacion_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentacion',
            old_name='detalles',
            new_name='sin_detalles',
        ),
    ]
