# Generated by Django 5.1.5 on 2025-02-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0023_rename_detalles_presentacion_sin_detalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicion',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
