# Generated by Django 5.1.5 on 2025-02-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0024_edicion_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicion',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
