# Generated by Django 5.1.5 on 2025-02-10 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0026_inicio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inicio',
            new_name='Configuracion',
        ),
    ]
