# Generated by Django 5.1.5 on 2025-02-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0027_rename_inicio_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='formato',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='participacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='periodo_inscripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='url_inscripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='fechas',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
