# Generated by Django 5.1.5 on 2025-02-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jjiapp', '0028_configuracion_formato_configuracion_participacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
